# Using Docker Compose Version 3 which support swarm deployment.

version: "3"
services:
  web:
    image: anandmohan777/helloworld:1
    depends_on: 
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
    ports:
      - "8080:8080"
    networks:
      - webnet

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=relayr
      - POSTGRES_PASSWORD=Passw0rd
    networks:
      - webnet

# Creating internal network from Docker Swarm.
networks:
  webnet:
